version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_name
      MYSQL_USER: username
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    environment:
      MAILDEV_WEB_USER: admin
      MAILDEV_WEB_PASS: password
      MAILDEV_INCOMING_USER: ''
      MAILDEV_INCOMING_PASS: ''
      MAILDEV_WEB_PORT: 1080
      MAILDEV_SMTP_PORT: 1025
    volumes:
      - mail-maildev-data:/var/lib/maildev
  app:
    depends_on:
      - mysqldb
      - maildev
    build: ./
    restart: unless-stopped
    ports:
      - 5000:5000
    stdin_open: true
    tty: true

volumes: 
  db:
  mail-maildev-data: