version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: traveller
    network_mode: "host"

  adminer:
    image: adminer
    restart: always
    network_mode: "host"
