# Local dev environment

version: "3.8"
services:

  web:
    build:
      context: ./web
      target: dev
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5000:5000
    networks:
      - traveller
    restart: "no"
    volumes:
      - "./web/traveller:/traveller"

  # Database Admin
  dbadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: "no"
    ports:
        - "8888:80"
    environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
        - ./volumes/pgadmin:/var/lib/pgadmin4/storage
    networks:
      - traveller

  # Database
  db:
    image: postgres:14.0
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/pg-data
    restart: "no"
    volumes:
      - "./volumes/postgres:/pg-data"
    networks:
      - traveller

  # Database Admin
  maildev:
    image: maildev/maildev
    restart: "no"
    networks:
      - traveller

networks:
  traveller: