# Local dev environment

version: "3.8"

volumes:
  db_data:
  dba_data:
  maildev_data:

services:

  web:
    build:
      context: ./web
      target: dev
    depends_on:
      - db
      - maildev
    env_file: ./config/.env.dev
    ports:
      - 5000:5000
    networks:
      - traveller
    restart: "no"
    volumes:
      - ./web/traveller:/traveller

  # Database Admin
  dbadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: "no"
    ports:
        - "8888:80"
    env_file: ./config/.env.dev
    volumes:
        - dba_data:/var/lib/pgadmin4/storage
    networks:
      - traveller

  # Database
  db:
    image: postgres:14.0
    env_file: ./config/.env.dev
    environment:
      - PGDATA=/pg-data
    restart: "no"
    volumes:
      - db_data:/pg-data
    networks:
      - traveller

  # Database Admin
  maildev:
    image: maildev/maildev
    restart: "no"
    volumes:
      - maildev_data:/var/lib/maildev
    networks:
      - traveller

networks:
  traveller: