"""empty message

Revision ID: 59faeaccde5b
Revises: 
Create Date: 2021-08-17 14:49:06.683427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59faeaccde5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cfp_start', sa.Date(), nullable=False),
    sa.Column('cfp_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('setting', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('setting')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('email_confirm_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('reviewer_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conf_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user_bridge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conf_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(length=300), nullable=False),
    sa.Column('description', sa.Text(length=3000), nullable=False),
    sa.Column('notes', sa.Text(length=200), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('accepted', sa.String(length=100), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('conf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conf_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conf_list_user_bridge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_list_id'], ['reviewer_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'reviewer_list_id')
    )
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=300), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('talk_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talk_list_author_bridge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_list_id'], ['author_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'author_list_id')
    )
    op.create_table('talk_list_score_bridge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['score_list_id'], ['score_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'score_list_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talk_list_score_bridge')
    op.drop_table('talk_list_author_bridge')
    op.drop_table('activities')
    op.drop_table('score_lists')
    op.drop_table('days')
    op.drop_table('conf_list_user_bridge')
    op.drop_table('author_lists')
    op.drop_table('talks')
    op.drop_table('schedules')
    op.drop_table('role_user_bridge')
    op.drop_table('reviewer_lists')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('conferences')
    # ### end Alembic commands ###
